name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

#      - name: Setup Java JDK
#        uses: actions/setup-java@v1.4.1
#        with:
#          java-version: 1.8
      - name: Setup JavaFX
        run: |
          apt update
          apt install openjfx
          export DISPLAY=:99.0

      - name: Run tests
        run: |
          ./gradlew check jacocoTestReport coveralls

      - name: Upload codecov report
        if: success()
        run: bash <(curl -s https://codecov.io/bash)
